site_name: WebKit Documentation

theme:
  name: material
  font: false
  logo: assets/WebKit.svg
  favicon: assets/WebKit.svg
  features:
    - header.autohide
    - search.share
    - navigation.tabs
    - navigation.tracking
    - content.action.edit

  icon:
    edit: material/pencil

plugins:
  - search
  - offline

repo_url: https://github.com/webkit/Documentation
edit_uri: blob/main/docs/

extra:
  social:
    - icon: fontawesome/brands/mastodon 
      link: https://front-end.social/@webkit

    - icon: fontawesome/brands/slack
      link: https://webkit.slack.com

    - icon: fontawesome/brands/github 
      link: https://github.com/webkit/webkit

    - icon: fontawesome/brands/safari
      link: https://webkit.org

  generator: false

copyright: WebKit and the WebKit logo are trademarks of Apple Inc.

markdown_extensions:
  - toc:
      permalink: true

extra_css:
  - stylesheets/webkit.css

